### ISSUE TITLE
Add healthcheck for all services

### ISSUE THREAD

**Issue by lancekuo** [lancekuo/terraform-docker-swarm#5]
In order to have an understanding in service health check, it'll be good to have this in every service I have been created.

Add `healthcheck` in all services.
```
    healthcheck:
      test: nc -z localhost 9090
      interval: 30s
      timeout: 30s
      retries: 3
```

- [x] ELK
- [x] Prometheus
- [ ] DFP
